const themes = [
    "Embracing Change",
    "Building Resilience",
    "The Power of Networking",
    "Overcoming Challenges",
    "Setting SMART Goals",
    "Mastering Time Management",
    "Effective Communication",
    "The Art of Feedback",
    "Continuous Learning",
    "Leadership Mindset",
    "Adaptability in the Workplace",
    "Mindfulness at Work",
    "The Impact of Positivity",
    "Nurturing Emotional Intelligence",
    "Strategic Decision-Making",
    "Balancing Work and Life",
    "Cultivating Creativity",
    "Strengthening Team Collaboration",
    "Innovative Problem-Solving",
    "Personal Branding",
    "Resolving Conflicts Professionally",
    "The Power of Mentorship",
    "Building Professional Relationships",
    "Cultivating a Growth Mindset",
    "Effective Public Speaking",
    "Leadership by Example",
    "Confidence in the Workplace",
    "Managing Stress",
    "The Importance of Feedback",
    "Financial Literacy for Growth",
    "Building a Strong Work Ethic",
    "Networking for Success",
    "Striving for Excellence",
    "Unlocking Creativity",
    "Building a Supportive Environment",
    "Adopting a Growth Mindset",
    "The Role of Self-Reflection",
    "Embracing Diversity",
    "The Power of Gratitude",
    "Goal Alignment in Career",
    "Maximizing Productivity",
    "Finding Passion in Work",
    "Effective Team Leadership",
    "Innovating for Success",
    "Personal Accountability",
    "Cultivating Professional Presence",
    "Emotional Resilience",
    "The Impact of Listening",
    "Overcoming Imposter Syndrome",
    "Finding Motivation Daily",
    "The Power of Visualization",
    "Effective Conflict Resolution",
    "Balancing Ambition and Patience",
    "Building a Personal Board of Advisors",
    "Cultivating a Positive Mindset",
    "The Importance of Professional Development",
    "The Art of Delegation",
    "Building Confidence in Networking",
    "Strategic Planning for Success",
    "The Impact of Gratitude on Success",
    "Effective Decision-Making",
    "Navigating Workplace Politics",
    "The Role of Empowerment",
    "Cultivating Work-Life Harmony",
    "Adopting a Proactive Mindset",
    "Mastering the Art of Follow-Up",
    "Effective Leadership Communication",
    "Overcoming Procrastination",
    "The Influence of Company Culture",
    "Cultivating Professional Curiosity",
    "Building Trust in Professional Relationships",
    "Staying Resilient in Tough Times",
    "Goal Setting for Personal Growth",
    "Embracing Diversity in Thought",
    "The Impact of Positive Habits",
    "Mindful Decision-Making",
    "Finding Joy in the Journey",
    "Building a Growth-Oriented Team",
    "The Power of Graciousness",
    "Effective Presentation Skills",
    "Cultivating a Supportive Work Environment",
    "The Role of Self-Confidence",
    "The Art of Receiving Feedback",
    "Strategic Career Planning",
    "Building a Culture of Accountability",
    "Networking with Purpose",
    "The Influence of Self-Reflection",
    "Adapting to Remote Work Challenges",
    "Overcoming Communication Barriers",
    "Cultivating a Strong Work Ethic",
    "Navigating Cross-Cultural Communication",
    "The Impact of Professional Development",
    "Building a Growth-Oriented Mindset",
    "Leadership through Collaboration",
    "The Journey to Continuous Improvement"
  ];
  

  module.exports = {themes};